(cl:in-package sdv_serial-msg)
(cl:export '(HEADER-VAL
          HEADER
          ENERGIZED-VAL
          ENERGIZED
          STAND_BY-VAL
          STAND_BY
          ROTATE-VAL
          ROTATE
          TURN_LEFT-VAL
          TURN_LEFT
          TURN_RIGHT-VAL
          TURN_RIGHT
          REVERSE-VAL
          REVERSE
          FORWARD-VAL
          FORWARD
          LOW_BATT-VAL
          LOW_BATT
          EMERGENCY_STOP-VAL
          EMERGENCY_STOP
          RESET_PC-VAL
          RESET_PC
          POWEROFF_PC-VAL
          POWEROFF_PC
          OBSTACLE_STOP-VAL
          OBSTACLE_STOP
          OVER_LOAD-VAL
          OVER_LOAD
          CONNECTION_ERROR-VAL
          CONNECTION_ERROR
          TAG_DISCONNECTED-VAL
          TAG_DISCONNECTED
          TAG_INIT-VAL
          TAG_INIT
          TAG_IS_ON_PLATFORM-VAL
          TAG_IS_ON_PLATFORM
          TAG_READ_ERROR-VAL
          TAG_READ_ERROR
          TAG_WRITE_ERROR-VAL
          TAG_WRITE_ERROR
          TAG_CLOSE-VAL
          TAG_CLOSE
          NOT_CONNECTION_ERROR-VAL
          NOT_CONNECTION_ERROR
          CONNECTION_ERROR_IMU-VAL
          CONNECTION_ERROR_IMU
          CONNECTION_ERROR_MSP-VAL
          CONNECTION_ERROR_MSP
          CONNECTION_ERROR_RFID-VAL
          CONNECTION_ERROR_RFID
          CONNECTION_ERROR_ULT-VAL
          CONNECTION_ERROR_ULT
          CONNECTION_ERROR_BATT-VAL
          CONNECTION_ERROR_BATT
))