// Generated by gencpp from file sdv_serial/battery.msg
// DO NOT EDIT!


#ifndef SDV_SERIAL_MESSAGE_BATTERY_H
#define SDV_SERIAL_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdv_serial
{
template <class ContainerAllocator>
struct battery_
{
  typedef battery_<ContainerAllocator> Type;

  battery_()
    : header()
    , current_main(0)
    , voltage_main(0)
    , current_laser(0)
    , voltage_laser(0)  {
    }
  battery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_main(0)
    , voltage_main(0)
    , current_laser(0)
    , voltage_laser(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _current_main_type;
  _current_main_type current_main;

   typedef uint32_t _voltage_main_type;
  _voltage_main_type voltage_main;

   typedef uint32_t _current_laser_type;
  _current_laser_type current_laser;

   typedef uint32_t _voltage_laser_type;
  _voltage_laser_type voltage_laser;





  typedef boost::shared_ptr< ::sdv_serial::battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdv_serial::battery_<ContainerAllocator> const> ConstPtr;

}; // struct battery_

typedef ::sdv_serial::battery_<std::allocator<void> > battery;

typedef boost::shared_ptr< ::sdv_serial::battery > batteryPtr;
typedef boost::shared_ptr< ::sdv_serial::battery const> batteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdv_serial::battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdv_serial::battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdv_serial::battery_<ContainerAllocator1> & lhs, const ::sdv_serial::battery_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current_main == rhs.current_main &&
    lhs.voltage_main == rhs.voltage_main &&
    lhs.current_laser == rhs.current_laser &&
    lhs.voltage_laser == rhs.voltage_laser;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdv_serial::battery_<ContainerAllocator1> & lhs, const ::sdv_serial::battery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdv_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::battery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::battery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdv_serial::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcf3e17e1084d22d987c211f14da987c";
  }

  static const char* value(const ::sdv_serial::battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcf3e17e1084d22dULL;
  static const uint64_t static_value2 = 0x987c211f14da987cULL;
};

template<class ContainerAllocator>
struct DataType< ::sdv_serial::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdv_serial/battery";
  }

  static const char* value(const ::sdv_serial::battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdv_serial::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# battery.msg\n"
"\n"
"Header header\n"
"uint32 current_main\n"
"uint32 voltage_main\n"
"uint32 current_laser\n"
"uint32 voltage_laser\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sdv_serial::battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdv_serial::battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_main);
      stream.next(m.voltage_main);
      stream.next(m.current_laser);
      stream.next(m.voltage_laser);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdv_serial::battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdv_serial::battery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_main: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_main);
    s << indent << "voltage_main: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.voltage_main);
    s << indent << "current_laser: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_laser);
    s << indent << "voltage_laser: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.voltage_laser);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDV_SERIAL_MESSAGE_BATTERY_H
