// Generated by gencpp from file sdv_serial/encoder.msg
// DO NOT EDIT!


#ifndef SDV_SERIAL_MESSAGE_ENCODER_H
#define SDV_SERIAL_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdv_serial
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : header()
    , rpm_left(0)
    , rpm_right(0)
    , motor_current_left(0)
    , motor_current_right(0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rpm_left(0)
    , rpm_right(0)
    , motor_current_left(0)
    , motor_current_right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _rpm_left_type;
  _rpm_left_type rpm_left;

   typedef int32_t _rpm_right_type;
  _rpm_right_type rpm_right;

   typedef int32_t _motor_current_left_type;
  _motor_current_left_type motor_current_left;

   typedef int32_t _motor_current_right_type;
  _motor_current_right_type motor_current_right;





  typedef boost::shared_ptr< ::sdv_serial::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdv_serial::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::sdv_serial::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::sdv_serial::encoder > encoderPtr;
typedef boost::shared_ptr< ::sdv_serial::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdv_serial::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdv_serial::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdv_serial::encoder_<ContainerAllocator1> & lhs, const ::sdv_serial::encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rpm_left == rhs.rpm_left &&
    lhs.rpm_right == rhs.rpm_right &&
    lhs.motor_current_left == rhs.motor_current_left &&
    lhs.motor_current_right == rhs.motor_current_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdv_serial::encoder_<ContainerAllocator1> & lhs, const ::sdv_serial::encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdv_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdv_serial::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90f42d76d2f804a6ce733d6653f63794";
  }

  static const char* value(const ::sdv_serial::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90f42d76d2f804a6ULL;
  static const uint64_t static_value2 = 0xce733d6653f63794ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdv_serial::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdv_serial/encoder";
  }

  static const char* value(const ::sdv_serial::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdv_serial::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# encoder.msg\n"
"\n"
"Header header\n"
"int32 rpm_left\n"
"int32 rpm_right\n"
"int32 motor_current_left\n"
"int32 motor_current_right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sdv_serial::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdv_serial::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rpm_left);
      stream.next(m.rpm_right);
      stream.next(m.motor_current_left);
      stream.next(m.motor_current_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdv_serial::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdv_serial::encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rpm_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rpm_left);
    s << indent << "rpm_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rpm_right);
    s << indent << "motor_current_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_current_left);
    s << indent << "motor_current_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_current_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDV_SERIAL_MESSAGE_ENCODER_H
