// Generated by gencpp from file sdv_serial/flexiforce.msg
// DO NOT EDIT!


#ifndef SDV_SERIAL_MESSAGE_FLEXIFORCE_H
#define SDV_SERIAL_MESSAGE_FLEXIFORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdv_serial
{
template <class ContainerAllocator>
struct flexiforce_
{
  typedef flexiforce_<ContainerAllocator> Type;

  flexiforce_()
    : header()
    , front_left(0)
    , front_right(0)
    , back_left(0)
    , back_right(0)  {
    }
  flexiforce_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , front_left(0)
    , front_right(0)
    , back_left(0)
    , back_right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _front_left_type;
  _front_left_type front_left;

   typedef uint32_t _front_right_type;
  _front_right_type front_right;

   typedef uint32_t _back_left_type;
  _back_left_type back_left;

   typedef uint32_t _back_right_type;
  _back_right_type back_right;





  typedef boost::shared_ptr< ::sdv_serial::flexiforce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdv_serial::flexiforce_<ContainerAllocator> const> ConstPtr;

}; // struct flexiforce_

typedef ::sdv_serial::flexiforce_<std::allocator<void> > flexiforce;

typedef boost::shared_ptr< ::sdv_serial::flexiforce > flexiforcePtr;
typedef boost::shared_ptr< ::sdv_serial::flexiforce const> flexiforceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdv_serial::flexiforce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdv_serial::flexiforce_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdv_serial::flexiforce_<ContainerAllocator1> & lhs, const ::sdv_serial::flexiforce_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.front_left == rhs.front_left &&
    lhs.front_right == rhs.front_right &&
    lhs.back_left == rhs.back_left &&
    lhs.back_right == rhs.back_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdv_serial::flexiforce_<ContainerAllocator1> & lhs, const ::sdv_serial::flexiforce_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdv_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::flexiforce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::flexiforce_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::flexiforce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::flexiforce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::flexiforce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::flexiforce_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdv_serial::flexiforce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f72264109dc46f89ab08fae02832706b";
  }

  static const char* value(const ::sdv_serial::flexiforce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf72264109dc46f89ULL;
  static const uint64_t static_value2 = 0xab08fae02832706bULL;
};

template<class ContainerAllocator>
struct DataType< ::sdv_serial::flexiforce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdv_serial/flexiforce";
  }

  static const char* value(const ::sdv_serial::flexiforce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdv_serial::flexiforce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# flexiforce.msg\n"
"\n"
"Header header\n"
"uint32 front_left\n"
"uint32 front_right\n"
"uint32 back_left\n"
"uint32 back_right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sdv_serial::flexiforce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdv_serial::flexiforce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.front_left);
      stream.next(m.front_right);
      stream.next(m.back_left);
      stream.next(m.back_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flexiforce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdv_serial::flexiforce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdv_serial::flexiforce_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "front_left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_left);
    s << indent << "front_right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.front_right);
    s << indent << "back_left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.back_left);
    s << indent << "back_right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.back_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDV_SERIAL_MESSAGE_FLEXIFORCE_H
