// Generated by gencpp from file sdv_serial/motors.msg
// DO NOT EDIT!


#ifndef SDV_SERIAL_MESSAGE_MOTORS_H
#define SDV_SERIAL_MESSAGE_MOTORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdv_serial
{
template <class ContainerAllocator>
struct motors_
{
  typedef motors_<ContainerAllocator> Type;

  motors_()
    : header()
    , left_percent(0.0)
    , right_percent(0.0)  {
    }
  motors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_percent(0.0)
    , right_percent(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_percent_type;
  _left_percent_type left_percent;

   typedef double _right_percent_type;
  _right_percent_type right_percent;





  typedef boost::shared_ptr< ::sdv_serial::motors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdv_serial::motors_<ContainerAllocator> const> ConstPtr;

}; // struct motors_

typedef ::sdv_serial::motors_<std::allocator<void> > motors;

typedef boost::shared_ptr< ::sdv_serial::motors > motorsPtr;
typedef boost::shared_ptr< ::sdv_serial::motors const> motorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdv_serial::motors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdv_serial::motors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdv_serial::motors_<ContainerAllocator1> & lhs, const ::sdv_serial::motors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_percent == rhs.left_percent &&
    lhs.right_percent == rhs.right_percent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdv_serial::motors_<ContainerAllocator1> & lhs, const ::sdv_serial::motors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdv_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::motors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::motors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::motors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdv_serial::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e58c5a22817d4395c3b395712a961a60";
  }

  static const char* value(const ::sdv_serial::motors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe58c5a22817d4395ULL;
  static const uint64_t static_value2 = 0xc3b395712a961a60ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdv_serial::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdv_serial/motors";
  }

  static const char* value(const ::sdv_serial::motors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdv_serial::motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# motors.msg\n"
"\n"
"Header header\n"
"float64 left_percent\n"
"float64 right_percent\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sdv_serial::motors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdv_serial::motors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_percent);
      stream.next(m.right_percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdv_serial::motors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdv_serial::motors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_percent: ";
    Printer<double>::stream(s, indent + "  ", v.left_percent);
    s << indent << "right_percent: ";
    Printer<double>::stream(s, indent + "  ", v.right_percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDV_SERIAL_MESSAGE_MOTORS_H
