// Generated by gencpp from file sdv_serial/tag_rfid.msg
// DO NOT EDIT!


#ifndef SDV_SERIAL_MESSAGE_TAG_RFID_H
#define SDV_SERIAL_MESSAGE_TAG_RFID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sdv_serial
{
template <class ContainerAllocator>
struct tag_rfid_
{
  typedef tag_rfid_<ContainerAllocator> Type;

  tag_rfid_()
    : header()
    , process()
    , product()
    , start_point()
    , end_point()  {
    }
  tag_rfid_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , process(_alloc)
    , product(_alloc)
    , start_point(_alloc)
    , end_point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _process_type;
  _process_type process;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _product_type;
  _product_type product;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _start_point_type;
  _start_point_type start_point;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _end_point_type;
  _end_point_type end_point;





  typedef boost::shared_ptr< ::sdv_serial::tag_rfid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdv_serial::tag_rfid_<ContainerAllocator> const> ConstPtr;

}; // struct tag_rfid_

typedef ::sdv_serial::tag_rfid_<std::allocator<void> > tag_rfid;

typedef boost::shared_ptr< ::sdv_serial::tag_rfid > tag_rfidPtr;
typedef boost::shared_ptr< ::sdv_serial::tag_rfid const> tag_rfidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdv_serial::tag_rfid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdv_serial::tag_rfid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdv_serial::tag_rfid_<ContainerAllocator1> & lhs, const ::sdv_serial::tag_rfid_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.process == rhs.process &&
    lhs.product == rhs.product &&
    lhs.start_point == rhs.start_point &&
    lhs.end_point == rhs.end_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdv_serial::tag_rfid_<ContainerAllocator1> & lhs, const ::sdv_serial::tag_rfid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdv_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::tag_rfid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdv_serial::tag_rfid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::tag_rfid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdv_serial::tag_rfid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::tag_rfid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdv_serial::tag_rfid_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdv_serial::tag_rfid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3f9c1da1f4087a6c5d53653731980dc";
  }

  static const char* value(const ::sdv_serial::tag_rfid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3f9c1da1f4087a6ULL;
  static const uint64_t static_value2 = 0xc5d53653731980dcULL;
};

template<class ContainerAllocator>
struct DataType< ::sdv_serial::tag_rfid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdv_serial/tag_rfid";
  }

  static const char* value(const ::sdv_serial::tag_rfid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdv_serial::tag_rfid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# tag_rfid.msg\n"
"\n"
"Header header\n"
"string process\n"
"string product\n"
"string start_point\n"
"string end_point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sdv_serial::tag_rfid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdv_serial::tag_rfid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.process);
      stream.next(m.product);
      stream.next(m.start_point);
      stream.next(m.end_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tag_rfid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdv_serial::tag_rfid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdv_serial::tag_rfid_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "process: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.process);
    s << indent << "product: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.product);
    s << indent << "start_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.start_point);
    s << indent << "end_point: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.end_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDV_SERIAL_MESSAGE_TAG_RFID_H
